# Generated by Django 5.2.4 on 2025-07-26 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0002_secret_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="owner",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="secret",
            name="encrypted_value",
        ),
        migrations.AddField(
            model_name="secret",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="vault.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secret",
            name="value",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="environment",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="secret",
            name="key",
            field=models.CharField(max_length=255),
        ),
    ]
